### ISSUE TITLE
[Help] How to query five oldest files that I edited/modified?

### ISSUE THREAD

**Issue by Quorafind** [jplattel/obsidian-query-language#1]
Thanks for building such a awesome plugin ! It worked perfectly when I tried your query sample🤩. 

However, sorry I do want to know: Is it possible to query five oldest files that I edited/modified?
I tried this:
```oql
name: Test
query: "Blabla"
template: "table"
sort: '-modified'
limit: 10
badge: false
fields: ['title', 'modified']
```
And it showed the created files.

[]Or it would be nice that you file a short document to show/introduces variables that can be used in query.

**Comment by jplattel** [comment]
Hey @Quorafind, I'm planning to add a list of parameters with documentation in the next release! Would that help you out? :)

**Comment by Quorafind** [comment]
Yep, you are so nice! Tks😁
