### ISSUE TITLE
2.0.0 fails to install from inside app

### ISSUE THREAD

**Issue by luckman212** [jplattel/obsidian-query-language#12]
Looks like a 404 on the `manifest.json` ?

![image](https://user-images.githubusercontent.com/1992842/109442027-ff807a80-7a04-11eb-8345-b771a7cdd055.png)

![image](https://user-images.githubusercontent.com/1992842/109442030-014a3e00-7a05-11eb-8301-19697895b920.png)

![image](https://user-images.githubusercontent.com/1992842/109442106-3a82ae00-7a05-11eb-9aa1-5db1168d5d53.png)

**Comment by jplattel** [comment]
Huh, interesting, I've pushed the 2.0.0, but made no official release yet. Still it's showing up in the repository...  That's why it's returning a 404. Will run the release right now :)

**Comment by jplattel** [comment]
Allright, the release it set. Obsidian should now be able to find it again: https://github.com/jplattel/obsidian-query-language/releases/tag/2.0.0 :)
