### ISSUE TITLE
Show preview in table?

### ISSUE THREAD

**Issue by piotryordanov** [jplattel/obsidian-query-language#14]
Currently, I am able to get the content of a note displayed in the table as such: 
![image](https://user-images.githubusercontent.com/48773775/110257804-17797080-7fa8-11eb-9812-ab03418196a8.png)

Would it be possible tho, to show the preview of the note? Because otherwise, the `content` does not show pictures: 
![image](https://user-images.githubusercontent.com/48773775/110257821-2d873100-7fa8-11eb-88db-5136cb005c95.png)

**Comment by jplattel** [comment]
It might be possible to do, but it might result in a recursive loop, ie matching a note that matches the note with the query, itself containing a query. Thus I'm unable to offer a solution that's safe right now...
