### ISSUE TITLE
Inconsistent results in OQL vs obsidian search results

### ISSUE THREAD

**Issue by jorgb** [jplattel/obsidian-query-language#16]
I am using 2.0.0 and the results are inconsistent with what I get when I perform a search in Obsidian itself.

For example: 

```oql
name: Paintings
query: 
	$and:
		- content: "tag:#artbook"
		- content: "tag:#painting"
template: "list"
```

Shows me 3 results.

When I search in Obsidian with **tag:#artbook  tag:#painting** I get 27 results.

So the indexing is not consistent with the results. Right now since the results are inconstent, the plugin becomes unreliable and counts and hits are not representative to what is really in my database.

I know you are working to make it better, but it looks like indexed results are not consistent with Obsidian's result. Is there maybe a way to reindex?

Just a side note, I used TiddlyWiki for a while, and they have a language where you can "program" results to filter. Either collapse the results to a count, or display them as a list, or feed them to a template.

They are called "tiddler filters" and they have a syntax like;

```
<$list filter="[tag[ListWidget]sort[title]]"/>
```

It seems you are trying to accomplish similar with the plugin as well. So I wanted to toss it in for inspiration; 

https://tiddlywiki.com/static/Filters.html

They are quite powerful, and would truly like to see in obsidian some day.

**Comment by jplattel** [comment]
Hey @jorgb!

Thanks for the feedback! The query block statement for OQL is an "AND" statement, meaning that the notes matched should have both tags. While the query in the Obsidian search is an "OR", meaning that the notes should contain at least 1 of the tags. Can you confirm this by changing `&and` into `$or`?

Otherwise it is indeed a indexing bug that needs investigation..

As for the filters in TiddlyWiki, I didn't know of those, will be looking into it! 👍

**Comment by jplattel** [comment]
Alright, I'm mistaken, the search you supplied does run as an AND search. Will have a look on why this isn't working correctly!

**Comment by jplattel** [comment]
Could you try the following:

````
```oql
name: Paintings
query: 
	$and:
		- content: "'#artbook"
		- content: "'#painting"		
template: "list"
```
````

The way OQL queries doesn't exactly match Obsidian since I'm using a different search engine.

**Comment by jorgb** [comment]
Hi @jplattel 
Yes that one produces the exact amount of hits. Could you tell me why there is a single quote needed in front of the hashtag but not at the end? 

The results I get are now consistent;

```
// Debugging OQL, total results: 27
// Query: 
{
  "$and": [
    {
      "content": "'#artbook"
    },
    {
      "content": "'#painting"
    }
  ]
}
```

But when I do not specify the quotes the string looks exactly the same, so this;

```
name: Paintings
query: 
	$and:
		- content: "#artbook"
		- content: "#painting"		
template: "list"
debug: true
```

Returns the same query expansion, with only five hits;

```
// Debugging OQL, total results: 5
// Query: 
{
  "$and": [
    {
      "content": "#artbook"
    },
    {
      "content": "#painting"
    }
  ]
}
// Results: 
```

**Comment by jplattel** [comment]
The single quote has to do with the way you search with Fuse. There's more information here: https://fusejs.io/examples.html#extended-search :)
