### ISSUE TITLE
Query syntax for current directory

### ISSUE THREAD

**Issue by pdxrlk** [jplattel/obsidian-query-language#17]
Thanks for the plugin, very useful. I am looking for some more examples of search syntax, and the fuse docs don't really help.

Specifically: how can I "find all notes in the same directory as the current note" ?  Neither of the two strings below work as expected.   

```oql
name: list notes
query: `"."
template: list
```

```oql
name: list notes
query: `"./"
template: list
```

**Comment by jplattel** [comment]
Hey @pdxrlk,

It's not possible to work with relative paths within Fuse, as it's matching on text only, not complicated parts as paths. If you know the foldername before hand I would suggest constructing the following query:

```
name: "list notes"
query: 
    path: "'<foldername>" 
template: "list"
```

Replace the `<foldername>` with your folder and notice the `'` before the string to make an exact match.

**Comment by pdxrlk** [comment]
Thanks!

From: Joost Plattel ***@***.***>
Date: Saturday, April 3, 2021 at 4:21 AM
To: jplattel/obsidian-query-language ***@***.***>
Cc: pdxrlk ***@***.***>, Mention ***@***.***>
Subject: Re: [jplattel/obsidian-query-language] Query syntax for current directory (#17)

Hey @pdxrlk<https://github.com/pdxrlk>,

It's not possible to work with relative paths within Fuse, as it's matching on text only, not complicated parts as paths. If you know the foldername before hand I would suggest constructing the following query:

name: "list notes"

query:

    path: "'<foldername>"

template: "list"

Replace the <foldername> with your folder and notice the ' before the string to make an exact match.

**Comment by jplattel** [comment]
Alright, closing this :)

**Comment by pdxrlk** [comment]
Thanks much.
