### ISSUE TITLE
Not being able to create tables (TypeError)

### ISSUE THREAD

**Issue by KierPrev** [jplattel/obsidian-query-language#23]
Hi, I copied this example:

```oql
name: Oldest projects
query: "'200 Projects/"
template: "table"
sort: '-created'
limit: 5
badge: false
fields: ['title', 'modified']
```
(And changed the query), but I'm getting the error:
```
TypeError: fields.forEach is not a function
```

Restarted Obsidian, and reinstalled the plugin, but I can't make it work.
Template "list" and "string" are working perfectly.

**Comment by jplattel** [comment]
Huh, that's strange, if the array is empty, the forEach should just not cycle through any of the items.. I'll add a check for an array in the next version!
