### ISSUE TITLE
Clarify how to use Logical Query Operators?

### ISSUE THREAD

**Issue by NeighNeighNeigh** [jplattel/obsidian-query-language#6]
Hey again, 

I am trying to get OQL to list all notes that contain the strings "[[Blender]]" and "#SoftwareTechnique"

I started off using the following syntax:
`query: "[[Blender]]" $and "#SoftwareFeature"`

And then tried:
```
query:
  $and:
  - "[[Blender]]"
  - "#SoftwareFeature"
```
But sadly neither of these has worked.

-------

My current code is as follows:
````markdown
```oql
name: 'List #SoftwareFeatures'
query:
  $and:
  - "[[Blender]]"
  - "#SoftwareFeature"
template: "list"
badge: false
debug: true
```
````

With the debug output showing no results:
```
// Debugging OQL, total results: 0
// Query: [object Object]
// Results: 
```

and I can confirm running the following search in Obsidians search pane returns the results I am after: `"[[Blender]]" "#SoftwareFeature"`

Could you please help explain how to get this up and running?

**Comment by jplattel** [comment]
Hey @NeighNeighNeigh! 

Thanks for creating this issue, I'm planning to document more on the query building and seeing where the friction arises is useful for me! 

As for the query you described I could make it work with:

````markdown
```oql
name: "testing"
query:
	$and:
		- content: "'#SoftwareFeature"
		- content: "'[[Blender]]"
template: 'list'
debug: true
```
````

This does result in #5 which includes the current note. The next version should have a switch for that, so I'll tackle that in that issue :)

**Comment by NeighNeighNeigh** [comment]
Thanks, unfortunately when I use the above code, I only get one result - that being the current note.
<img width="770" alt="image" src="https://user-images.githubusercontent.com/4795315/106400334-de625380-6471-11eb-8ab9-93a6ff34abea.png">

**Comment by NeighNeighNeigh** [comment]
Ah okay seems the problem is it will only show a not containing "[[Blender]]" if it's not part of a longer string. For example the following is not found "# Render with multiple machines in [[Blender]]"

I tried removing the ' before [[Blender]] also, but that didn't help

**Comment by jplattel** [comment]
Mmh, interesting! I did indeed try it out locally without putting it in an entire string.. I will try to reproduce it! Thanks for the extended feedback so far! :)

**Comment by jplattel** [comment]
Alright, I've gained some additional information on this issue. I think it has to do with the way the data is cached within Obsidian which I then use to build the index. It seems like such specific query operators are somewhat unstable and depended on a good index... 

Will investigate some more and hopefully reach a solution soon :)

**Comment by jplattel** [comment]
@NeighNeighNeigh in version 2.0.0 I've switched to a different property for indexing the content, if possible could you try again? The queries seems to work for me right now :)
