### ISSUE TITLE
Can't use plugin with error 

### ISSUE THREAD

**Issue by BigbadHort** [jplattel/obsidian-query-language#7]
Hi
I can't use plugin with error : 
TypeError: Cannot read property 'search' of undefined

Could you help me please

my system - Win10  Obsidian 0.10.11

**Comment by jplattel** [comment]
Hey @BigbadHort , could you include the queryblock that you use? That will help out figuring out where the error is :)

**Comment by gammak** [comment]
Seeing the same issue here. Sample query:


```oql
name: "Daily notes"
query: "'daily/'"
template: "{name}: {count}"
debug: true
```

Yields, in the preview, 

TypeError: Cannot read property 'search' of undefined
// Debugging OQL, total results: 0
// Query: 'daily/'
// Results: 


Seeing similar results after changing the query to "'./'" and the template to "{count}"

**Comment by cmjn14** [comment]
Hi, I have the same issue
running Obsidian V0.10.11

My query:

```
```oql
query: "'AUTHORS/"          
template: "list"
debug: true
```
```

In the preview:
TypeError: Cannot read property 'search' of undefined
// Debugging OQL, total results: 0
// Query: 'AUTHORS/
// Results: 

In the console:

Uncaught TypeError: Cannot read property 'remove' of undefined
    at FuseSearchIndex.removeFile (eval at <anonymous> (app.js:1), <anonymous>:1907:33)
    at ObsidianQueryLanguagePlugin.refreshFile (eval at <anonymous> (app.js:1), <anonymous>:27095:25)
    at eval (eval at <anonymous> (app.js:1), <anonymous>:27064:27)
    at t.e.tryTrigger (app.js:1)
    at t.e.trigger (app.js:1)
    at t.trigger (app.js:1)
    at t.onChange (app.js:1)
    at e.trigger (app.js:1)
    at e.<anonymous> (app.js:1)
    at app.js:1

**Comment by jplattel** [comment]
Are these issues still persisting? It might have to do with the OQL block running before the index is build. Can you confirm with the latest version of the plugin: 1.5.0?

**Comment by cmjn14** [comment]
I tried quickly with a very simple query this morning and it works fine :-)
I'll try more complex queries later
Thanks!!!

**Comment by blongty** [comment]
I had the issue too after installing the plugin. Closing and reopening Obsidian appears to have fixed the problem.

**Comment by jplattel** [comment]
Alright! In version [2.0.0](https://github.com/jplattel/obsidian-query-language/releases/tag/2.0.0) this should be solved! In the case that the indexing isn't done yet a better warning in shown instead of 'search' is undefined. Closing this :)
